version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: kivikot/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db

  frontend:
    image: kivikot/taski_frontend
    env_file: .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/

  gateway:
    image: kivikot/taski_gateway
    volumes:
      - static:/staticfile/
    ports:
      - "8000:80"
